### ISSUE TITLE
一个关于本地化的特性

### ISSUE THREAD

**Issue by Ginsway** [Nova-Committee/Quit#1]
![image](https://user-images.githubusercontent.com/106016532/205438726-660a4622-8892-445e-965a-033ca6f1d786.png)
![image](https://user-images.githubusercontent.com/106016532/205438730-6c434b0e-95a0-448c-8c54-a91bea0a8be6.png)
-------------------------------------------------------------------------------------
当遇到前置缺失的提示时，Quit的退出界面似乎没有正确加载本地化文件。

**Comment by Ginsway** [comment]
补充：mc版本1.18.2，模组版本1.0.1

**Comment by Ginsway** [comment]
1.19.2也有此bug

**Comment by VulpesStella** [comment]
好像也可以简单修一下，但是只能在找不到键时默认显示英文。
