### ISSUE TITLE
Modrinth page

### ISSUE THREAD

**Issue by Shywizz** [Nova-Committee/Quit#10]
If you don't mind going registering a creator's account over at [modrinth.com](https://modrinth.com), publishing your mod there would be appreciated !

**Comment by VulpesStella** [comment]
I have one, just forgot to repost it on modrinth😶

**Comment by VulpesStella** [comment]
Sorry, I just realized I've posted [it](https://modrinth.com/mod/quit) long long ago. Now I'm updating the files to the latest.
