### ISSUE TITLE
1.8.9 and 1.16.5 Version

### ISSUE THREAD

**Issue by epic0421** [Nova-Committee/Quit#4]
Noticed that this mod supported older versions such as 1.7.10 and would be appreciated if 1.8.9 was one of those versions. Thank you :)

Edit: 1.16.5 Forge too

**Comment by VulpesStella** [comment]
Okay, it's planned now. I'll make a reply when it's done.

**Comment by VulpesStella** [comment]
@epic0421 For 1.16.5, check [this](https://www.curseforge.com/minecraft/mc-mods/quitconfirm).

**Comment by VulpesStella** [comment]
1.8.9 is ready. Try [this](https://github.com/Nova-Committee/Quit/actions/runs/4520148325) out, and I'll release it soon.

**Comment by epic0421** [comment]
> 1.8.9 is ready. Try [this](https://github.com/Nova-Committee/Quit/actions/runs/4520148325) out, and I'll release it soon.

Works great!
