### ISSUE TITLE
[BUG]在高版本，点击模组按钮，弹出退出提示

### ISSUE THREAD

**Issue by Ginsway** [Nova-Committee/Quit#7]
环境：
Minecraft：1.20.1 1.19.4
Forge：47.1.36 45.1.16
Quit：1.0.0

**Comment by Ginsway** [comment]
游戏暂停菜单，点模组提示是否退出世界，点自带的退出直接退出世界

**Comment by VulpesStella** [comment]
已在 1.1.0 修复
