### ISSUE TITLE
[1.19.2-Forge] No lang translation if game crashes

### ISSUE THREAD

**Issue by Christofmeg** [Nova-Committee/Quit#8]
Version: 1.19.2-1.0.1

If the game crashes for some other reason and the player tries to quit the game, they get the warning "menu.quit.quitGame"

![image](https://github.com/Nova-Committee/Quit/assets/4357405/326be10e-73a2-4cd0-b3e4-d42f94c952c5)

**Comment by VulpesStella** [comment]
Duplicate #1
